### ISSUE TITLE
An email template is not sent for an abandoned cart

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#100]
For a guest cart abandoned on 15 Sep, 2016 12:12 PM, I have in total 5 email templates:
Test 2	2 Hours After Abandonment
Test 3	3 Hours After Abandonment
Test email template		1 Days After Abandonment	
Test 4	2 Days After Abandonment
Reminder for your cart	3 Days After Abandonment

I got the emails from Test 2, Test email template, Test 4 & Reminder for your cart email templates.

But I did not get the email from Test 3 email template.

http://screencast.com/t/MOo7t0MTw

**Comment by Chetna1510** [comment]
Emails were not sent for the "Test 3" Email Template due to header issue. When I have changed the email address on the same site in "Send From This Email Address" field with my email address, I have received the email for "Test 3" email template. I am not able to replicate the issue.
