### ISSUE TITLE
Getting error on deleting the plugin from the plugin page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#102]
Deleting the plugin from the Plugin page, I am getting this error.
http://screencast.com/t/KpwDIpABLxqT

**Comment by Chetna1510** [comment]
I have deleted the plugin from WordPress plugin's page. But I am not getting this error.

**Comment by Chetna1510** [comment]
The issue is not for the latest version. So, I am closing this issue.
