### ISSUE TITLE
Getting a blank record in the Abandoned Orders

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#119]
There are 2 records which are blank. These carts were abandoned on 30 Jun, 2016 12:50 PM and 29 Jun, 2016 02:52 PM.
Abandoned blank records: http://prntscr.com/e56ehj

When checked the cart details, there is a notice displayed.
http://prntscr.com/e56d6s & http://prntscr.com/e56eow

**Comment by Chetna1510** [comment]
This issue has been fixed in commit: bf48e3aabe46a93ef50c798d93fd920f69f212b1
