### ISSUE TITLE
A new cart abandoned after placing an order on the current date still has the status Abandoned

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#122]
A cart was abandoned with the cart id 140 on 7th Feb. It is a guest cart. The cart was recovered on 7th Feb itself. A new cart is abandoned again for the same email id on the same date (Cart id 141). A new record is added on the Abandoned Order tab. After the cron job is run, the status of the order is still 'Abandoned' whereas it should be 'Abandoned but new cart created after this'.

New abandoned cart: http://prntscr.com/e5ii0c
Order placed: http://prntscr.com/e5ii59

**Comment by Chetna1510** [comment]
I had abandoned a cart as a guest user using "patelchetna1122+2@gmail.com" email address. Then I have recovered the cart. See the screenshot: https://www.screencast.com/t/mYqNYdsYbCeM

After that, I have again abandoned a cart with the same email address and my cart is being disaplyed on Abandoned Orders tab. 

When the cron time is run, the status of the cart has been changed to 'Abandoned but new cart created after this'. See the screenshot: https://www.screencast.com/t/d3QX0mDHy

I am closing this issue as I have not replicated this issue.
