### ISSUE TITLE
Change default cut-off time to 10 minutes & template sending times

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/Woocommerce-abandon-cart-lite#124]
Change default cut-off time to 10 minutes.

1st email template time: 15 minutes
2nd email template time: 2 hours
3rd email template time: 24 hours.

**Comment by Chetna1510** [comment]
In the Abandoned Cart lite version, we are not creating 3 default email template. We have only one default email template. Also, we do not give email template time frequency in minutes.
