### ISSUE TITLE
Notice is received when i add variable product 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#173]
When i add any variable product, and that variable product is abandoned after cut off time over then this order comes into Abandoned Orders.So when i click view order Notice is received.

https://www.screencast.com/t/FxELVK70Y

**Comment by Chetna1510** [comment]
I had added a variable product to cart as a registered user.  But I do not receive an error message on the Abandoned Cart details page.

Screenshot: https://www.screencast.com/t/MPuol1atQL7
Hence, I am closing this issue.
