### ISSUE TITLE
Two record are shown on Recovered Order tab 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#175]
When i recovered any product from email recovery email then i saw two entry for each recovery.

Now this issue is not replicated https://www.screencast.com/t/p4ep5qv2U

**Comment by Chetna1510** [comment]
This issue has been fixed in commit: c4d84a74b3fad73f1c861c21ed563935a86de50c

So, I am closing this issue.
