### ISSUE TITLE
The status of the cart should not be 'Abandoned but new cart created after this' when a new cart is abandoned after an order is placed on the same date

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#183]
The status of the cart should not be 'Abandoned but new cart created after this' when a new cart is abandoned after an order is placed on the same date.

Instead, we should create a new status for such a case. As here there is no new cart abandoned.

**Comment by Chetna1510** [comment]
We will add this as an enhancement in the LITE with PRO version.

**Comment by pinalj** [comment]
If a cart has been created on the same day on which an order has been received, it will continue to be marked as cart_ignored = 1
