### ISSUE TITLE
Carts are considered abandoned even after an order is placed with the same user 

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#188]
For a logged in user, when a cart is abandoned and recovered, if on the same date I am abandoning a new cart, then the new cart is still getting considered as Abandoned, whereas in the next cron run after the cart is abandoned, the cart status should have been changed to 'Abandoned but new cart created after this'.

Also, reminder emails are getting sent to the customer for the new cart abandoned.

Steps:
1. I abandoned a cart and recovered the cart from the email.
Order placed: http://staging.tychesoftwares.com/woo_khyati3/wp-admin/post.php?post=3254&action=edit
2. Then I abandoned a new cart for the same user. The cart was considered as abandoned (Cart id 3). Then I updated the abandoned cart by adding a new product to cart. Now the cart id 3's status is changed to 'Abandoned but new cart created after this'. And a new cart is abandoned (Cart id 6). After the cron run, the status of the cart is not changed.
Abandoned order: http://prntscr.com/fd9u45
3. I also got reminder emails for the cart id 6. http://prntscr.com/fd9v7r

**Comment by pinalj** [comment]
Unable to replicate in the current copy. The new cart records are being marked as cart_ignored = 1
