### ISSUE TITLE
Front end page loading continually with more than 3 attributes

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#217]
Here i try one variable product with more than 3 attributes selected then product front end load continues.
 
when i try in woo_bkap_next_release the product front end load continues
this is my variation setting: https://www.screencast.com/t/1RssPfuw
the front end of the product: https://www.screencast.com/t/DpaoQa0dJW
http://staging.tychesoftwares.com/woo_bkap_next_release/wp-admin/post.php?post=6767&action=edit
The above setting i test with all plugin deactivate and also try with abandoned cart lite plugin activate

when i try the same setting in local site then it works fine
This is my variation setting: https://www.screencast.com/t/vv4OBOZpjA
the front end page work properly: https://www.screencast.com/t/0ropsuzqsq

The above setting i test with all plugin deactivate and with our plugin activate both the case it works fine

**Comment by Chetna1510** [comment]
I have checked ( http://staging.tychesoftwares.com/woo_bkap_next_release ) site. Once we select attributes it takes few seconds while our plugin is deactivated or activated.

The issue is not from our plugin. And I am able to add the product to the cart.
