### ISSUE TITLE
Reminder email not received when i am testing with php 7.1.7

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#221]
Here when i abandon any cart then reminder email not received. Here i try with logged in user and Guest user. 
But i received test email, Even i reduced the cron job minutes into 5 min.

Please check and let me know

**Comment by vishalck** [comment]
@apeksha10 Since when is this happening? DId you ever receive abandoned cart emails from your local earlier?
