### ISSUE TITLE
Wrong cart details of guest customer was populated on the checkout page.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#227]
Client has raised an issue that wrong cart details have been populated on the checkout page when the user comes to the site from abandoned cart reminder email.

Forum page: https://www.tychesoftwares.com/forums/topic/abandoned-cart-lite-abandoned-cart-email-sent-in-error-with-wrong-shipping-det/

Ticket number: 21400

I have checked on his site that Glen Locklear had abandoned a cart as a guest user using email address mission@fbcwentzville.com. When the Glen is clicked on the link in the abandoned cart reminder email, and go to the checkout page, the checkout page showing the cart content of Sharon Micciche who is Logged-in user.

Please see the screenshot of abandoned cart reminder email, the client had shared with me: https://www.screencast.com/t/l13qraqaOqS
See the screenshot of checkout page: https://www.screencast.com/t/UxRFoLy8

When I had checked on his site to prevent this issue, guest user's user ID was #14. And option name "wcal_guest_user_id_altered" was "Yes".

**Comment by bhavik-kiri** [comment]
For version 4.4 we have given a condition if the guest id's are wrong then we will not send them abandoned cart reminder emails.

**Comment by ashokrane** [comment]
What is the meaning of this setting "wcal_guest_user_id_altered" ?

**Comment by bhavik-kiri** [comment]
"wcal_guest_user_id_altered" This option is set when we have a wrong guest id's and then we run a alter query to make that wrong id correct.

So once this alter query is successfully executed we set an option "wcal_guest_user_id_altered".

**Comment by Chetna1510** [comment]
Yes, we have given a condition if the guest id's are wrong then we will not send them abandoned cart reminder emails.

So, I am closing this issue.
