### ISSUE TITLE
Integrate cart with One page Checkout plugin

### ISSUE THREAD

**Issue by bhavik-kiri** [TycheSoftwares/Woocommerce-abandon-cart-lite#241]
I have abandoned logged in cart and guest cart with the One-page checkout plugin.

For both, the customer's cart was captured as per our plugin behavior.

Also, Abandoned cart reminder email has been sent to them.

But when I come to website from the reminder emails, it opens the standard WC cart page and checkout page.

What do we need to do with it?

When we send the email, we generate the URL for the cart page, so at that time we have to check if the  Product in the cart is available in the One-page checkout setting or not.

If the product is present then we need to show the one-page checkout for that cart/product.

**Comment by ashokrane** [comment]
For Lite version, we can do this later. First let's implement in PRO & see how it's being used or how much it's being used by adding it to our stats that we are gathering.

**Comment by ashokrane** [comment]
On another note, let's not add this to the Lite version.
