### ISSUE TITLE
While adding new email templated then by default it should be deactive

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#242]
Here when i try to add more than one email template with different time  on chrome browser then by default it displays deactive

https://www.screencast.com/t/vCMMZ3W2

**Comment by ashokrane** [comment]
The default behaviour is correct. We do want the templates to remain deactivated when they are added. However, here we could add a message on the Listing page where we are showing the template added success message that: "In order to start sending this email to your customers, please activate it."
