### ISSUE TITLE
Duplicate records are displayed in Recovered orders tab Loggedin users recover cart.

### ISSUE THREAD

**Issue by bhavik-kiri** [TycheSoftwares/Woocommerce-abandon-cart-lite#264]
I have abandoned cart for a logged in user and I have received the abandoned cart reminder email for it. Then in another browser ( firefox ) I have deleted all cache and opened that abandoned cart. I have placed the order without any changes.

After placing the order I have 2 records on the recovered orders tab:
1. https://prnt.sc/hsuamr

I have checked in Database that when I reach the order received a page, it creates the blank record for the same logged in user, it shows order id in the blank captured record too.
1. https://prnt.sc/hsubns

I have Settings:
1. https://prnt.sc/hsu76y

I have also changed the cron time to 2 minutes as well as the template time to 2 minutes.

**Comment by Chetna1510** [comment]
This issue has been fixed in the commit: c4d84a74b3fad73f1c861c21ed563935a86de50c

Hence, I am closing this issue.
