### ISSUE TITLE
Update failed when updating from v4.4 to v.4.5

### ISSUE THREAD

**Issue by kartikparmar** [TycheSoftwares/Woocommerce-abandon-cart-lite#282]
I have WooCommerce Print Invoice & Delivery Note plugin installed on my site.
Updating Abandoned Cart Lite for WooCommerce from v4.4 to v.4.5 and it's showing error as shown in below screenshot.
https://prnt.sc/i4shei

One of the clients reported the issue but not sure if this is the same issue or not.
https://wordpress.org/support/topic/redirect-problem-33/

**Comment by Chetna1510** [comment]
I am unable to replicate the same issue with the latest version of our plugin. Screenshot: https://www.screencast.com/t/3w5UKYZli
