### ISSUE TITLE
Deleted orders are displayed as Recovered on 1 Jan 1970 on the Order Recovered tab

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#3]
When a recovered order is deleted permanently, the order record should not be displayed on the Order Recovered tab. 

Currently the deleted order is displayed on the Order Recovered tab in this manner: http://screencast.com/t/OdjpIVt3W7Pl

**Comment by Chetna1510** [comment]
I have tried to replicate the issue on my local server. But I am unable to replicate this issue.

I have abandoned a cart and receive abandoned cart reminder email. Then I come to the site through abandoned cart reminder email and place an order. So, my cart is being disaplyed on Recovered Orders tab. 
Screenshot: https://www.screencast.com/t/f4TI2XHVG

Then I had deleted the orders permanently from WooCommerce. But my recovered cart is not being disaplyed on Recovered Orders tab. 

Screenshot: https://www.screencast.com/t/cTW4zqSbSv2

I have checked it with guest user and logged-in user both.

I am closing this issue as I am unabled to replicate this issue.
