### ISSUE TITLE
Got a notice for Deprecated warning on the Abandoned Orders tab

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#30]
On installing and activating the plugin, on the Abandoned Orders tab, I am getting this warning for a deprecated feature.
http://screencast.com/t/0L5S7IbKvz

**Comment by Chetna1510** [comment]
I have activated a fresh copy of our plugin with PHP 7.1.7, but I am not getting the same error on Abandoned Orders tab.

Also, the error message is showing for the "pagination.php" file. The same file we have removed from our plugin. So, I am closing this issue.
