### ISSUE TITLE
The Abandoned Orders tab is not displaying the abandoned orders

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#31]
I abandoned a cart as a logged in user, the DB has the record of it, yet it is not showing the record on the Abandoned Orders tab.

**Comment by Chetna1510** [comment]
I am not able to replicate the same issue with the latest version of the plugin with php 7.0.9. Screenshot: https://prnt.sc/k4ppii
