### ISSUE TITLE
Change default email header text for email template

### ISSUE THREAD

**Issue by ashokrane** [TycheSoftwares/Woocommerce-abandon-cart-lite#312]
I noticed that the default email header text for the default email text is set to "Abandoned Cart Email Template". If that is correct, then please change it. This is very unprofessional & a very bad default choice for a title.

**Comment by Chetna1510** [comment]
This is not correct. The default Email Template Header Text is set to "Abandoned cart reminder" text. 

Screenshot: https://www.screencast.com/t/trGIdXa0Oj0

Hence I am closing this issue.

**Comment by Chetna1510** [comment]
Yes. sure sir. I will discuss with Dhruvin.
