### ISSUE TITLE
The email header is coming different due to the cart URL

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#34]
An email template's body is coming stretched due to the cart link added to the email. The same template is coming fine when a new cart's email template is received.

Stretched email: http://screencast.com/t/ZK2xdPwcjr 
Normal email: http://screencast.com/t/6Of0NsZ5EO

This is happening only in Thunderbird. If the same emails are opened in Gmail, then the email body is not coming stretched.

**Comment by dhruvins** [comment]
Cart Links will not be inserted directly in the reminder emails. Cart Links otherwise working fine.
