### ISSUE TITLE
2 cart create when I use logged in user email id

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#369]
2 cart create when I use logged in user email id.
Fresh install

steps to replicate this issue:
1. Set 1 in Cart abandoned cut-off time
2. Cart abandoned as guest users
3. After cut off time passed then 2 carts created.1 cart from logged in users and 2 from guest

https://www.screencast.com/t/ZerfY37OuR6
https://www.screencast.com/t/pdNZsnCWErLa
https://www.screencast.com/t/iUBK4DaKsa

**Comment by pinalj** [comment]
The registered user cart is for the admin user. When the plugin is installed and the admin is logged into his account, if any products are present in the cart then the cart will be tracked. This is the way we expect the plugin to work. Hence closing the issue.
