### ISSUE TITLE
{{products.cart}} Table Not Responsive

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#377]
Email templates are not responsive
Abandoned cart screenshot : https://www.screencast.com/t/bqjSKKfq
 I have checked the abandoned cart reminder email and check on Outlook on Android Mobile device.
but product cart is not responsive. ( cart abandoned as guest users in chrome browser)
see the screenshot: https://files.slack.com/files-pri/T10SWE9DH-FC2ULE70V/screenshot_20180804-162932.png
tickets : https://wordpress.org/support/topic/products-cart-table-not-responsive/

**Comment by Chetna1510** [comment]
We have added new responsive default email template. So, I am closing this issue. 
Commit: 435785376a2032cceb112fb9d99abcbea5326da6
