### ISSUE TITLE
2 lite plugin activated together then error found "redirected you too many times."

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#378]
Steps to replicate that issue
Create new database
1. Install an old version of Abandoned cart lite that is 4.9
2. Install an old version of Arconix FAQ that is 1.8.1
3. Activate both plugins 
4. Now go to Dashboard-update and using the multi-checkbox. Update both plugins
5.Now clcik on "Ruturn plugin page" link
An error found "redirected you too many times."
https://www.screencast.com/t/uYV7fWys4mY

tickets for the reference : https://wordpress.org/support/topic/the-plugin-prevents-access-to-the-wp-backend-after-update-to-v-5-0-1/#post-10554268

**Comment by apeksha10** [comment]
The same issue replicate another 2 lite plugin that is Order Delivery Date lite and Product Delivery Date lite
Follow above same steps

**Comment by pinalj** [comment]
No longer an issue as the Welcome page is no longer a part of the plugin.
