### ISSUE TITLE
Link need to be change on the welcome page. As it shows 404 errors.

### ISSUE THREAD

**Issue by bhavik-kiri** [TycheSoftwares/Woocommerce-abandon-cart-lite#379]
Following links needs to be change on the welcome page. As it shows 404 errors.

These all posts are need to be directed to docs domain

1. https://www.tychesoftwares.com/capturing-abandoned-carts-woocommerce-abandoned-cart-pro-plugin/?utm_source=wpaboutpage&utm_medium=link&utm_campaign=AbandonedCartLitePlugin

2. https://www.tychesoftwares.com/understanding-the-default-email-templates-of-abandoned-cart-pro-for-woocommerce-plugin/?utm_source=wpaboutpage&utm_medium=link&utm_campaign=AbandonedCartLitePlugin

**Comment by pinalj** [comment]
The Welcome page is no longer a part of the plugin, hence closing.
