### ISSUE TITLE
Abandoned cart status should be updated if the user place an order for the same day.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#384]
I had checked on the client site that the customer has placed an order on "25 August at 2:33 PM" with 3 products.

Screenshot: http://prntscr.com/kqu3rv

And the Abandoned Cart has been created on 25 August at 2:47 PM with the same 3 products. Screenshot: http://prntscr.com/kqu4oo

User details: http://prntscr.com/kqu5l3

**Comment by ashokrane** [comment]
@Chetna1510 Please do not work on this until & unless it's clear on how are we going to handle it.

**Comment by pinalj** [comment]
One possible scenario where this issue can occur (the same cart is created for a user after an order has already been placed) is if a guest user becomes a registered user when placing the order.

This scenario was recently discovered in the PRO version. We will apply a similar fix for the LITE version for the same scenario.

Issue: https://github.com/TycheSoftwares/woocommerce-abandoned-cart-pro/issues/1703
Commit: https://github.com/TycheSoftwares/woocommerce-abandoned-cart-pro/commit/84dc55eb98b07b35c3cdbffece1e755d0dc0d96f

Similar tests should be performed to ensure things continue to work smoothly.
