### ISSUE TITLE
Cannot enable the email template if the Site Language is Hebew.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#395]
If the site language is Hebrew then toggle button to activate the email template shows the ON/OFF button.

Screenshot: http://prntscr.com/ladjh9

**Comment by apeksha10** [comment]
With the Hebrew language when I click on "On" and "Off" button then it is not displayed correctly
see the video: https://www.screencast.com/t/jEOjLotu7S6
But after refreshing the page then it is working fine

I think we should display Toggle button

Hence re-open this issue

**Comment by Chetna1510** [comment]
I am unable to replicate this issue. I have updated the plugin and then changed the SITE language in Hebrew. Also, I have checked the issue with the fresh install and the Site URL was already in the Hebrew language. Screenshot: http://prntscr.com/lc8j9g

So, I am closing this issue.
