### ISSUE TITLE
Getting a fatal error on Product report page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#40]
When I have Lite & Pro version, both enabled, on the Product Report tab I am getting a fatal error. http://screencast.com/t/K5RZhzrJ

And the records from Product report tab is removed from the lite plugin.

**Comment by Chetna1510** [comment]
Now, we cannot activate both the plugin's together. As we have added "Migrate the date of LITE to PRO" feature. 

Also, we have changed the class name "WCAL_Product_Report_Table" from "WCAP_Product_Report_Table" in the latest version. 

So, the same error message will not be displayed in our plugin. So, I am closing this issue.
