### ISSUE TITLE
Getting following error message in the debug log file

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#400]
Fatal error: Uncaught Error: Call to undefined function hash() in /wp-content/plugins/woocommerce-abandoned-cart/cron/wcal_send_email.php:259

**Comment by pinalj** [comment]
Unable to replicate the issue. Also, the client agreed to get in touch with us if the issue was replicated with the latest version. Since we have not heard back from the client in a few months, it's safe to assume that things are working fine. Hence closing the issue.
