### ISSUE TITLE
Duplicate records shows on recovered order tab

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#402]
Cart abandoned as Guest users

Steps to replicate this issue
1. Cart abandoned as Guest users
2. listed in Abandoned order tab
3. Received reminder email
4. click on checkout link and recovered the cart
5. Recovered order tab shows duplicate entry
6. Abandoned order tab remove that cart

Note: Cart Abandoned time shows different time

see the screenshot :  https://www.screencast.com/t/uyTCcN9If

**Comment by pinalj** [comment]
Unable to replicate the issue on staging.
