### ISSUE TITLE
Empty records getting inserted after every order placed

### ISSUE THREAD

**Issue by dhruvintyche** [TycheSoftwares/Woocommerce-abandon-cart-lite#412]
Place a normal order and check lite history database. A new empty record with data as `{"cart":[]}` was getting inserted.

Also create a script to delete the older such records as they are redundant.

**Comment by apeksha10** [comment]
With latest git copy still, I am found 1 records in database
please check this and take appropriate action @dhruvintyche @pinalj @ashokrane
