### ISSUE TITLE
Getting a fatal error on the Order received page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#42]
When Lite & Pro version both are enabled, I am getting a fatal error on the Order received page. And the records from Lite plugin is removed. http://screencast.com/t/c7ki35AVQW

**Comment by Chetna1510** [comment]
We could not activate both the plugin's together. As we have added "Migrate the date of LITE to PRO" feature.

Also, we have changed the class name "wcal_Recover_Orders_Table" from "WCAP_Recover_Orders_Table" in the latest version.

So, the same error message will not be displayed in our plugin. So, I am closing this issue.
