### ISSUE TITLE
404 errors from welcome page

### ISSUE THREAD

**Issue by dhruvintyche** [TycheSoftwares/Woocommerce-abandon-cart-lite#425]
Frequent 404 from Welcome page

/404.html?page=/capturing-abandoned-carts-woocommerce-abandoned-cart-pro-plugin/?utm_source=wpaboutpage&from=https://www.rollingstoned.co.il/

**Comment by dhruvins** [comment]
Welcome page commented and removed, hence 404 errors wont come.
