### ISSUE TITLE
Please add the following string to one string.

### ISSUE THREAD

**Issue by komal-maru** [TycheSoftwares/Woocommerce-abandon-cart-lite#427]
Please add the following parts of strings into one string.

The strings are present in the woocommerce-ac.php file at line number 2918, 2923, 2929, 2936

Attaching a screenshot: http://prntscr.com/lxsl9b

**Comment by komal-maru** [comment]
Also please check the string 'f you want to change the default invoice numbers & set some numbering scheme of your own, then you can set it here with a starting invoice number, a prefix & suffix.' for which 'I' is missing for If word.

**Comment by komal-maru** [comment]
Also please correct the correct the following word (piece) which is a typo error: 
#: includes/wcal_admin_notice.php:37
msgid "<div id=\"wcal_update\" class=\"updated woocommerce-message\" style=\"padding:15px;\"><span>We need to update your email template database for some improvements. Please take a backup of your databases for your peice of mind</span><span class=\"submit\"><a href=\"%s\" class=\"button-primary\" style=\"float:right;\">Update</a></span></div>"

**Comment by apeksha10** [comment]
The above string is missing in pot file

hence re-open this issue
