### ISSUE TITLE
Cart were not deleted from Abandoned order tab and reminder email send the customer with cancelled order

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#428]
Steps to replicate this issue
1. I have abandoned a cart as a logged-in user
2. Reminder email received
3. click on checkout link and select Paypal payment gateway
4. Just came to the paypal login page and closed the window( Didn't pay the payment).
5. Then I have manually changed the order status "Pending" to "Canceled" from WooCommerce-order page

The cart should be removed from Abandoned order tab and reminder email should not send

see the screenshot: https://www.screencast.com/t/ZcjWwa5NkhG

**Comment by pinalj** [comment]
Unable to replicate with the latest version. The cart record is being deleted from the table.

**Comment by apeksha10** [comment]
With the latest git copy, received Fatal error
follow the same steps as the issue has
after changing the order status "Pending" to "Canceled" from WooCommerce-order page then found a fatal error

Fatal error: Uncaught Error: Call to a member function get() on null in C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce-abandoned-cart\includes\wcal-common.php:763 Stack trace: #0 C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce-abandoned-cart\includes\frontend\wcal_checkout_process.php(446): wcal_common::wcal_get_cart_session('user_id') #1 C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce-abandoned-cart\includes\frontend\wcal_checkout_process.php(403): Wcal_Checkout_Process->wcal_updated_recovered_cart('22', 4694, '10', Object(WC_Order)) #2 C:\xampp\htdocs\acpro\wp-includes\class-wp-hook.php(288): Wcal_Checkout_Process->wcal_order_complete_action('processing', 4694) #3 C:\xampp\htdocs\acpro\wp-includes\plugin.php(208): WP_Hook->apply_filters('processing', Array) #4 C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce\includes\class-wc-order.php(290): apply_filters('woocommerce_pay...', 'processing', 4694, Object(WC_Order)) #5 C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce\includes\class-wc-order.php(269 in C:\xampp\htdocs\acpro\wp-content\plugins\woocommerce-abandoned-cart\includes\wcal-common.php on line 763

https://www.screencast.com/t/1JZXpg43

hence re-open this issue
