### ISSUE TITLE
All the settings are coming same for lite Settings tab when Pro plugin is installed

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#43]
When Lite & Pro both are enabled, the settings tab from both the versions are coming the same even when both the versions have different fields available.

Pro Settings tab: http://screencast.com/t/0Q5ERYQv1EY
Lite Settings tab: http://screencast.com/t/wYznb3gn

**Comment by ashokrane** [comment]
Not applicable anymore. Migration script is built & released in v7.5 of Pro plugin.
