### ISSUE TITLE
Recovered Details are being updated on Recovered Orders tab once we place an order as a logged-in user. 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#430]
**Describe the bug**
We have recovered 1 cart on the site. And then again we try to place an order, recovered details are being updated into the existing recovered order on Recovered Orders tab

**To Reproduce**
1. I have abandoned a cart as a guest user on 2019-01-23 at 9:39 AM
2. received an abandoned cart reminder email
3. I came to the site from email and recovered the cart on 2019-01-23 9:52 AM - I became the registered user while recovering the cart( Username: Chetna )
4. then after some time, I logged in to the site( Username: Chetna ) and again abandoned a cart as the same logged-in user 
5. after the cart abandoned cut off time, I have placed an order on 2019-01-23 10:00 AM.
6. On the Recovered Orders tab, the recovered date and time has been updated.
Recovered time is 2019-01-23 10:00 AM.

**Expected behavior**
The recovered date and time should not be updated on the Recovered Orders tab.

**Screenshots or Video**
Screenshot of second order: http://prntscr.com/mavgjr , 1st order: http://prntscr.com/mavgo0

**Desktop (please complete the following information):**
 - Browser: Abandoned a cart and recovered the cart in Firefox and second time placed the order in incognito mode

**Isolating the problem (mark completed items with an [x]):**
 [ ] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**WordPress Environment**
WooCommerce version: 3.5.3
WordPress version: 5.0.3

**Comment by apeksha10** [comment]
The same issue replicated
steps to replicate this issue 
1. I have abandoned a cart as a guest user on 2019-01-23 at 9:39 AM
2. received an abandoned cart reminder email
3. I came to the site from email and recovered the cart.I became the registered user while recovering the cart( Just click on Create Account and put Password )
4. Don't close that browser and go to shop page
5. Again abandoned 1 cart 
6. After cut off time passed to place the order 
7. On the Recovered Orders tab, the recovered date and time has been updated.
