### ISSUE TITLE
Getting 403 Forbidden error message while updating or creating the email template

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#432]
**Describe the bug**
I am able to replicate the issue on my staging site. Our plugin is conflicting with the Wordfence Security plugin. When I have activated that plugin, I am not able to create/update the email template with the CSS. it will show the 403 Forbidden error message if the email template will have CSS.

**To Reproduce**
1. Activate WordFence security plugin
2. Edit/Add new email template which should have the CSS( <style type="text/css"> ) in the HTML Mode of Email Body section. 

**Expected behavior**
It should not show any error message if that plugin is activated or not.

**Screenshots or Video**
http://prntscr.com/maz07x

**Isolating the problem (mark completed items with an [x]):**
 [ ] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by dhruvins** [comment]
Wordfence protected mode by default blocks all the submissions containing `<script>` and `<style>` tags. Our templates have `<style>` tags which are blocked. Whitelisting the action once from here http://prntscr.com/maz07x wont show the 403 error again.

Other steps to whitelist are as below:
1. Change the firewall mode to Learning
2. Save the email template
3. Switch back the mode to Protected
4. Again try to edit and save. 403 error message will not come.

It will be best to not modify or alter the firewall programmatically to save the template.
