### ISSUE TITLE
Carts are not being captured of the guest user.

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#437]
**Describe the bug**

I have upgraded the plugin to the latest version 5.2.0 on woo_chetna.

I am trying to abandon a cart as a guest user on my site
**To Reproduce**
1. added product to the cart
2. entered first name and last name and email address on the checkout page.
3. the cart has been captured as visitor cart.. 

http://prntscr.com/mmogj2

getting error message in the console log: 

Uncaught ReferenceError: ajaxurl is not defined
    at HTMLInputElement.<anonymous> (wcal_guest_capture.min.js?ver=5.0.3:1)
    at HTMLInputElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLInputElement.r.handle (jquery.js?ver=1.12.4:3)

**Comment by apeksha10** [comment]
Same issue replicate from me..
I have old version that is 5.0.1 and update the plugin from plugin page
Try to abandoned as guest users
enter First name, Last name and email id on checkout page 
Visitor cart captured


Note: this is working fine when take latest git copy and paste on our site then Abandoned cart working fine
