### ISSUE TITLE
Getting a fatal error on the Email templates tab when Lite & Pro both are enabled

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#44]
When Lite & Pro both the plugins are enabled, on the Email templates tab, getting a fatal error. Also, the email templates from Lite plugin are no longer available.
http://screencast.com/t/sGgt3RpXdAL

**Comment by Chetna1510** [comment]
I am not able to replicate the same issue on woo_chetna. As we have changed the class name of wcal_Templates_Table for Lite version. 

http://screencast.com/t/cMfoTnia4ieD

**Comment by ashokrane** [comment]
Not applicable anymore. Migration script is built & released in v7.5 of Pro plugin.
