### ISSUE TITLE
Recovered order tab shows duplicate entry 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#441]
**Describe the bug**
Recovered order tab shows duplicate entry with Cart Recovered time same

**To Reproduce**
1. Cart Abandoned as guest users.
2. After cut off time passed an order to display on Abandoned order tab
3. Reminder email received
4. Click on Checkout link
5. place the order
6. Recovered order tab shows that order with correct time
7. After a few seconds when I refresh the Recovered order tab then it cart shows duplicate entry with the same Cart Recovered time but Abandoned cart time is different

**Expected behavior**
Recovered order tab shows only 1 order

**Screenshots or Video**
https://www.screencast.com/t/ytBnaBBECzcD

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by ashokrane** [comment]
@dhruvintyche @pinalj @Chetna1510 Wasn't this issue already fixed?
