### ISSUE TITLE
Getting a fatal error on Abandoned Orders tab when LIte & Pro are active

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#45]
When Lite & Pro, both versions are enabled, the Abandoned Orders tab has a fatal error. And the records from Lite version are removed too.

http://screencast.com/t/IJAtUXDdctTP

**Comment by Chetna1510** [comment]
I am not able to replicate the same issue on WOO_CHETNA. I have activated Lite & Pro version, Abandoned Orders tab is not displaying any error. And the record of the Lite version is displaying under the Abandoned Orders page.

http://screencast.com/t/csGPuSa3rDJ

**Comment by ashokrane** [comment]
Not applicable anymore. Migration script is built & released in v7.5 of Pro plugin.
