### ISSUE TITLE
Old abandoned cart deleted from Abandoned order tab with same email Id.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#455]
**Describe the bug**
Old abandoned cart deleted from Abandoned order tab when I put same email id on checkout page but the product is dofferent

**To Reproduce**
1. Cart abandoned as guest users
2. Go to checkout page put the first name last name and email id
3. Again go to another browser and abandoned the different product and on checkout page put First name' last name and the same email I which is put for the first cart abandoned 
3. After cut off time passed the old cart was deleted and new abandoned cart display which is wrong 

**Expected behavior**
Even if the same email id all cart should be displayed on abandoned order tab.

**Screenshots or Video**
WooCommerce set up : https://www.screencast.com/t/qJr9lVm3
https://www.screencast.com/t/Cd6b9CUINk
https://www.screencast.com/t/xjOIaCkWubg6

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by dhruvins** [comment]
This is a valid scenario to ignore the older cart that was abandoned. Many customers have complained regarding multiple emails being sent to a particular email address. In the Pro version, we can have more control over the emails being sent. Hence closing this as of now.
