### ISSUE TITLE
Logged in users cart was not display in Abandoned order tab

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#461]
**Describe the bug**
Logged in users carts was not display in Abandoned order tab

**To Reproduce**
1. Cart Abandoned as logged in users
2. After cut off time passed that cart was not display in Abandoned order tab

The above issue replicate randomly

Note: Because of this behavior not reminder email received

**Expected behavior**
Abandoned order tab should show all records

**Screenshots or Video**
https://www.screencast.com/t/QYF0ezoky ( here I abandoned 1 cart name as Vishal that cart ignored ) 
https://www.screencast.com/t/LtjNyVyT

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**Comment by dhruvins** [comment]
Once an order is placed with the same email, then we are not sending reminder emails to the same email.

In the Pro version, we need to create separate settings to have more control over such users who abandon carts even after placing orders. For example: Do not send these users reminder emails for the next 30 days, or never send emails to these users etc.
