### ISSUE TITLE
Email address was not capturing on one client site.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#482]
The email address was not capturing on one client site and hence the abandoned cart email was also not being sent.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/7509

**Isolating the problem (mark completed items with an [x]):**
[x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
[ ] This bug happens with a default WordPress theme active, or [Storefront]
[ ] I can reproduce this bug consistently using the steps above

NOTE: This issue is not replicated to us. I am able to replicate this issue on the client's site only.

**Comment by dhruvins** [comment]
committed in this patch: https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/commit/6586fe692052745cc039aa685ab35dbcf9ace569#diff-7c3b37cb2e29299fb5666fc7b4ea8674

Hence closing this issue.
