### ISSUE TITLE
Empty cart is showing when we visit the site through the Checkout link in the abandoned cart email.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#483]
**Describe the bug**
Empty cart is showing when we visit the site through the Checkout link in the abandoned cart email.

**To Reproduce**
1. I have abandoned a cart
2. I have received an abandoned cart email for my cart. 
3. I copied a checkout link from the email and open it in the private window but the cart is showing as empty.

**Expected behavior**
Originally abandoned cart should be displayed when we visit the site through the Checkout link in the Abandoned cart email.

**Screenshots**
https://www.screencast.com/t/ifA6nwSuGiq
https://www.screencast.com/t/ojTvOby52

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Comment by pinalj** [comment]
Unable to replicate with the latest versions of WP, WC & the plugin. Hence closing.

**Comment by apeksha10** [comment]
This issue still replicate on Multi site-fresh install testing
1. Cart Abandoned as guest users
2. After cut off time passed reminder email received
3. I copied a checkout link from the email and open it in the Incognito browser but the cart is showing as empty.

https://www.screencast.com/t/T18sKKqVtj
https://www.screencast.com/t/RQjwNNMQoCs

Hence re-open this issue

**Comment by pinalj** [comment]
Unable to replicate on staging/woo_kartik_multisite.
