### ISSUE TITLE
Reminder email does not received after updating site to WordPress 5.2

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#484]
Reminder emails does not receive  after updating the site WordPress 5.2
Testing on live site 5.3.4
steps:
1. I have abandoned 3 to 4 cart as guest users
2. after waiting to 15 to 20 min, not reminder email received 

screenshot of Abandoned order tab: https://www.screencast.com/t/clfOvci7NJE7
https://www.screencast.com/t/iscAnrQ4yzv

For logged in users I am able to received reminder email but wrong cart information load

**Comment by pinalj** [comment]
Reminder emails are being sent fine for guests & registered users with WP 5.2.3

**Comment by apeksha10** [comment]
With the latest git copy, Reminder emails come fine

Hence Fixed this issue.
