### ISSUE TITLE
Carts cannot be captured once we try to abandon it through the custom checkout page

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#485]
**Describe the bug**
I have installed "Aero: Custom WooCommerce Checkout Pages plugin on my local server. Using this plugin, I have created the checkout page. And when I am trying to abandon a cart from checkout page, AJAX didn't call and cart cannot be captured. 

This issue is informed by the client.

**To Reproduce**
1.Create a custom checkout page using the documentation here: https://buildwoofunnels.com/docs/aerocheckout/getting-started/replace-default-checkout/
2. Add products to cart
3. Go to checkout and fill information such as First Name, Last Name and Email.
These fields are not getting captured.

**Expected behavior**
The cart should be captured along with the details like First Name, Last Name, Emails and other fields usually getting captured.

**Screenshots or Video**
http://prntscr.com/nquqph

**Comment by apeksha10** [comment]
Re-opening this issue,
As after activating Aero: Custom WooCommerce Checkout Pages plugin, try to abandoned as guest users than the cart not be captured along with the details like First Name, Last Name.
https://www.screencast.com/t/QULkBm1RrWC
https://www.screencast.com/t/vNTjwyeJ8

**Comment by pinalj** [comment]
Scenarios tested:
**1. Aero Checkout enabled**:
Abandon the cart as a guest, enter the names & then the email address - all the details are saved correctly.

**2. Aero Checkout plugin enabled**:
Abandon a cart as a guest, enter the email address and then the names - the names are not captured.

**3. Aero Checkout plugin disabled**:
Abandon a cart as a guest, enter the email address and then the names - the names are not captured.

So the behavior of the plugin with Aero Checkout enabled and disabled is consistent and hence this is not an issue.

**Comment by apeksha10** [comment]
The original issue was whether Aero plugin is compatible with our plugin. But the issue where the first & last name was not captured in our plugin is fixed in the pro version because we don track that in the lite version
