### ISSUE TITLE
Getting a warning on the client site.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#487]
**Describe the bug**
Getting a warning "A non-numeric value encountered in wcal_send_email.php on line 46" on the home page of the client's site.

Note: I tried to replicate this issue at our end but I am unable to replicate it. This issue is occurring on the client's site. We did not get more details on the plugin set up or in which case the issue is coming etc. from the client.

Screenshot of the issue: https://sagone.es/wp-content/uploads/2019/06/Captura-de-pantalla-2019-06-10-a-las-11.48.45.jpg

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

**Comment by pinalj** [comment]
Ensure that the abandoned cart time is set to blanks when testing this.

**Comment by apeksha10** [comment]
I test the above issue with the below cases
1. set blanks to abandoned cart time
2. Put cut off time like some numeric value
3. Put some alphabetical value, but that is not being saved

so I am not able any error on my debug log file.
Hence Put a Fixed label
