### ISSUE TITLE
Basket word display in our plugin page settings

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#509]
Abandon Basket Lite- "BASKET " Word is display in our plugin setting page

see the screenshot: https://www.screencast.com/t/5JK0PxnJwarw

I am not sure why this word is displayed everywhere?  please let me know if any changes are made for our side.

**Comment by pinalj** [comment]
The word 'cart' is replaced by 'basket' on the admin end of the site. This happens when you set the site language to English (UK). When you set the language to English (US), the word 'basket' is replaced with 'cart'.

The same has been setup on staging.tychesoftwares.com/woo_apeksha

**Comment by apeksha10** [comment]
The above issue is still replicate on my local even if I change site language English (US) but on woo_apeksha if I change site language to English (US) then It is working fine.
If any client-facing the issue then we will re-open this issue.
right now I am putting Fixed label for this issue
