### ISSUE TITLE
Show a notice for exporting the plugin data from Lite to Pro version of the plugin

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#51]
When someone installs Pro version when the lite version is already added, then a notice should be added to allow the user to export the data from lite version to pro version.

This will ensure all the data from lite version is not lost in the process of upgrading the plugin.

The notice should have a Yes/ No links. Clicking on Yes should take you to a new page and show details of what all things will be exported to the Pro version.

**Comment by ashokrane** [comment]
This is done & implemented in Pro version in v7.5.
