### ISSUE TITLE
An error is occurring while creating the email templates on Multi-site environment.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#532]
**Describe the bug**
An error "There was a problem adding the email template. Please contact the plugin author" is occurring while creating the email templates on child sites of Multi-site. The default email template is also not present in the email templates section.

**To Reproduce**
1. I have installed and activated the Abandoned Cart Lite plugin on the Main site on Multisite network. 
2. Visited our plugin's tabs on one of the child sites.
3. The default email template was not present there so I tried creating the new email template but when I clicked on the Save Changes button, I got "There was a problem adding the email template. Please contact the plugin author" error.

**Expected behavior**
The default email template should be present and store owner should be able to create a new email template.

Video of the issue: https://www.screencast.com/t/KuAEuJhs

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [x] I can reproduce this bug consistently using the steps above

**WordPress Environment**
<details>
```
Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/10137

**Comment by Chetna1510** [comment]
@priyanka-tychesoftwares The default email templates will come when you activate our plugin from an individual site. @priyanka-tychesoftwares can you please activate the plugin from an individual site and check?

**Comment by priyanka-tychesoftwares** [comment]
@Chetna1510 Yes, the plugin is activated on individual site then also the mentioned issue is occurring.

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/commit/5436c404de71edbad709b09114ad2e1fe10efa0b
