### ISSUE TITLE
Admin users cart is not being captured and listed in the Abandoned order tab

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#535]
**Describe the bug**
Admin users cart is not being captured and listed in the Abandoned order tab

**To Reproduce**
1. Try to abandon cart as Admin users
2. After some time pass, the cart was not listed on the abandoned order tab

**Expected behavior**
Abandoned order tab should show the cart abandoned as an admin user

**Screenshots or Video**
https://www.screencast.com/t/cj1B7wvVhjt
https://www.screencast.com/t/xTAIsHFpMd

**Comment by pinalj** [comment]
Please ensure that GDPR choice for the registered user is not set to "Do not track the cart"
