### ISSUE TITLE
Loader for test email does not appear when I try to send test email on single site

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#548]
**Describe the bug**
Loader for test email does not appear when I try to send test email on a single site
Take latest git copy on 12-10-2019 at 11:00
**To Reproduce**
1. Single site testing
2. I have already one email template and try to send test email but loader was not appear

**Screenshots or Video**
https://www.screencast.com/t/FaakTH51

Note : Need to check on multi site

**Comment by pinalj** [comment]
Unable to replicate: https://www.screencast.com/t/CHlb08b72

**Comment by apeksha10** [comment]
With the latest git copy, I am unable to replicate that issue
