### ISSUE TITLE
Getting errors in debug.log file

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#55]
Getting below mentioned errors in debug.log file:

> [16-May-2016 09:15:21 UTC] PHP Notice:  Undefined variable: user_email_billing in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/cron/send_email.php on line 205
> 
> [16-May-2016 09:50:21 UTC] PHP Notice:  Undefined variable: email in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php on line 25
> 
> [16-May-2016 09:50:21 UTC] PHP Notice:  Undefined variable: email in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php on line 35
> 
> [16-May-2016 09:50:21 UTC] PHP Notice:  Undefined variable: email in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php on line 40
> 
> [16-May-2016 09:50:21 UTC] PHP Notice:  Undefined variable: email in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php on line 46
> 
> [16-May-2016 09:50:22 UTC] PHP Notice:  Undefined variable: email in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce/templates/emails/admin-new-order.php on line 51
> 
> [16-May-2016 10:05:08 UTC] PHP Notice:  Undefined index: user_id in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php on line 958
> 
> [16-May-2016 10:05:08 UTC] PHP Warning:  Invalid argument supplied for foreach() in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php on line 962
> 
> [16-May-2016 10:51:46 UTC] PHP Notice:  Undefined index: ship_to_billing in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce_guest_ac.class.php on line 89

**Comment by Chetna1510** [comment]
[16-May-2016 10:05:08 UTC] PHP Notice: Undefined index: user_id in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php on line 958

This issue has been fixed in the commit: 092e98c8a3a85094b9f8957fe3335f42f51be737

**Comment by Chetna1510** [comment]
[16-May-2016 10:05:08 UTC] PHP Warning: Invalid argument supplied for foreach() in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce-ac.php on line 962

This issue has been fixed in commit: 63a386c69f0c09ccf59334736702f767d3af6814

**Comment by Chetna1510** [comment]
[16-May-2016 11:09:44 UTC] PHP Notice: Undefined index: ship_to_billing in /home/tychesod/public_html/staging/woo_aclite/wp-content/plugins/woocommerce-abandoned-cart/woocommerce_guest_ac.class.php on line 89

This issue has been fixed in commit: 3a813fdf0a5e0e8da8959224fe90501717c34d6e

I am closing this issue. As all error notices have been fixed as mentioned above comments.
