### ISSUE TITLE
Guest users reminder email does not received

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#552]
**Describe the bug**
Guest users reminder email does not receive

**To Reproduce**
1. Try to abandoned as guest users
2. After cut off time passed then to reminder emails is not received

Note: Reminder email for logged in users work fine

**Comment by pinalj** [comment]
Unable to replicate. Reminder emails are being received for both guests & registered users.

**Comment by apeksha10** [comment]
Re-opening the above issue
Take latest git copy at 14-10-2019 at 16:48
Still, reminder emails for the guest cart are not received

**Comment by apeksha10** [comment]
With the latest git copy, I am unable to replicate this issue
Hence closed this issue
