### ISSUE TITLE
Email sending details are not shown on pop up view

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#553]
**Describe the bug**
Email sending details are not shown on pop up view

**To Reproduce**
1.  Just update the copy and test on this copy
2.  On the pop-up view model does not show email sending details whereas the same thing is shown when I test on multisite with a fresh install

A single site with update copy: https://www.screencast.com/t/vymHHlazi7
Multi-site with fresh install: https://www.screencast.com/t/z02a4Wlwo

**Comment by pinalj** [comment]
Unable to replicate this issue on a single site: https://www.screencast.com/t/AscWTPRa
