### ISSUE TITLE
Abandoned order records in Dashboard shows wrong data

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#555]
**Describe the bug**
Abandoned order records in Dashboard shows wrong data

**To Reproduce**
1. I have total 4 Abandoned orders
2. Recovered one of them
3. After refreshing the Dashboard-Abandoned order data shows 4 carts abandoned which is wrong 

**Expected behavior**
Dashboard-Abandoned order data should show 3 Carts only

**Screenshots or Video**
https://www.screencast.com/t/THdplcsMijWG
https://www.screencast.com/t/n36mzQxgFX
https://www.screencast.com/t/XkASj4AiW

**Comment by pinalj** [comment]
The recovered cart was abandoned at some stage in the cart cycle. Hence it should be counted as abandoned. 
Pro version works the same way. Hence closing.
