### ISSUE TITLE
Notice is shown on dashboard when I delete all carts from abandoned order tab

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#561]
**Describe the bug**
Notice is shown on the dashboard when I delete all carts from abandoned order tab

**To Reproduce**
1. Go to Abandoned order tab
2. Delete all carts with the help of Bulk action settings
3. after deleting all carts some notice is shown on the dashboard 

https://www.screencast.com/t/M6WQiSfM

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/issues/562
