### ISSUE TITLE
Change cron job-related information 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#589]
**Describe the bug**
change cron job-related information 

https://www.screencast.com/t/43ga8FyEut

**Comment by ashokrane** [comment]
@apeksha10 Please specify what information there should be changed & what is the new information that is expected to be put there.

**Comment by apeksha10** [comment]
If the above settings are disabled then the client need to create cron job manually.
So this issue is not valid

closing this issue
