### ISSUE TITLE
After recovering the cart, that cart is being again listed as abandoned with the Abandoned status .

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#592]
**Describe the bug**

**To Reproduce**
1. Abandoned the cart as Guest users and the cart has a Subscription product
2. Received the reminder email
3. After recovered the cart the automatically new cart generate with no email id and first name last name
4. Newly generate cart and recovered cart both Abandoned cart time same
see the screenshot: https://www.screencast.com/t/ZOEzgmLAZVB
https://www.screencast.com/t/nYrqoaeZPh8
https://www.screencast.com/t/EaXBNdxnNd

**Expected behavior**
No new cart should be captured after recovered the cart

**Comment by apeksha10** [comment]
The same issue replicate without subscription product
1. Abandoned cart as guest users
2. Reminder email received
3. Recovered the same cart
4. Refresh Abandoned order tab 
5. Refresh recovered order tab, you can see recovered order tab shows the cart is recovered which is correct
6. Again refresh Abandoned order tab, you can see the recovered cart again listed in Abandoned order tab with the status Abandoned

see the screenshots:   https://www.screencast.com/t/chdSXdVnm9
https://www.screencast.com/t/uNbmCCEqaLi
https://www.screencast.com/t/6eWuwwwI

you can check on woo_apeksha abandooned id :35

**Comment by pinalj** [comment]
The issue is replicated as below:

1. Abandon a guest cart

**Comment by apeksha10** [comment]
The latest git copy, I am not able to replicate the above issue
