### ISSUE TITLE
There should be a "Delete All" button present on the Abandoned Orders tab.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#609]
There should be a "Delete All" button present on the Abandoned Orders tab. So the store owners can delete multiple abandoned orders in one click.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14378

**Comment by pinalj** [comment]
Discussed with @dhruvins - We'll be adding a few bulk actions similar to Pro as below:
1. Delete All Carts
2. Delete All Visitor Carts
3. Delete All Guest Carts
4. Delete All Registered Carts.
