### ISSUE TITLE
Reminder email for guest user does not received with WC-4.0.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#610]
**Describe the bug**
Reminder email for guest user does not received with WC-4.0.

**To Reproduce**
1. An abandoned cart as guest users
2. WooCommerce 4.0 
3. I do not change any time on code
still. guest users reminder email does not receive whereas logged in users reminder email received fine

see the screenshot: https://www.screencast.com/t/yPPaGvlL2ULi

Note: I also check Guest users carts with WooCommerce 3.8.0 and it is working fine.

**Comment by pinalj** [comment]
WC: 4.0.0
AC Lite: 5.7.1
Received the reminder for guest users on staging/woo_pinal2: https://www.screencast.com/t/7mXUjAuP7L
