### ISSUE TITLE
The plugin strings are not translating to the Lithuanian language. They are displaying in the English only

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#613]
**Describe the bug**
The plugin strings are not translating to the Lithuanian language. The plugin strings are not translating to the Lithuanian language.

**To Reproduce**
1. I have created PO and MO files of our plugin in the Lithuanian language using POEDIT software. 
Added those files in the languages folder of our plugin and also, in the wp-content/languages folder. Then, I changed the site language to Lithuanian (Lietuvių kalba) from the General settings of WordPress.

But still, the plugin strings are displaying in the English instead of displaying in the Lithuanian language.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/14836

**Comment by pinalj** [comment]
Fixed in https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/commit/e826ea03a4a5fcc1519e00b1ef2c7c7d98ebb431
