### ISSUE TITLE
When the product is edited on the front-end, that product is listed on the Abandoned Orders Page.

### ISSUE THREAD

**Issue by kenil802** [TycheSoftwares/Woocommerce-abandon-cart-lite#617]
The client is having an issue when the particular product is edited on the front-end, then that product is listed on the Abandoned Orders list page of the plugin settings.

We are unable to replicate it on our site. The issue is coming on the client-side only.

Ticket link: https://tychesoftwares.freshdesk.com/a/tickets/16478

**Comment by dhruvins** [comment]
@pinalj please update the usage of the hook on the Wiki page for reference to support team and testing team

**Comment by apeksha10** [comment]
I added filter given in the wiki page, after applied that filter admin users restrict abandoned carts from being captured.
