### ISSUE TITLE
"Product has been deleted" message was displaying in the Abandoned Order for the visitor carts.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#623]
**Describe the bug**

**To Reproduce**
1. Abandon a cart as a visitor
2. The abandoned order for that cart will show a message "Product has been deleted".

**Screenshots or Video**
https://www.screencast.com/t/3G3zh1eDSf2

This issue was occurring because of the conflict with the plugin "Improved variable Product Attributes for WooCommerce".

[improved-variable-product-attributes.zip](https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/files/4770465/improved-variable-product-attributes.zip)

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [x] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/16606

**Comment by pinalj** [comment]
As discussed with @dhruvins , a simple '0do not break' test for carts containing variable products while the conflicting plugin is active and inactive should suffice.
