### ISSUE TITLE
Add order note when order is Recovred from email notifications

### ISSUE THREAD

**Issue by bhavik-kiri** [TycheSoftwares/Woocommerce-abandon-cart-lite#63]
Add the a order note That order note that order has been recovered. When order is placed via abandoned cart email notifications then add the note .

**Comment by Chetna1510** [comment]
We have added Order Note on WooCommerce Order page when order will be recovered by accessing the link from abandoned cart reminder email.

Please see the screenshot: https://www.screencast.com/t/FgRXmlia

So, I am closing this issue.
