### ISSUE TITLE
The record of cart abandoned by admin is lost after recovery

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#64]
The admin user abandoned a cart with these items: http://screencast.com/t/y2RbXKyc with the email id khyati@tychesoftwares.com on 18 May, 2016 09:42 AM. The cart id was 1.

Recovery Emails: http://screencast.com/t/JaZjD1cTgxLG & http://screencast.com/t/wpzpT57YCxu

Cart link in the recovery email: http://staging.tychesoftwares.com/woo_khyati/?wacp_action=track_links&validate=bAJ0ATXwO1eo9hrmuq/u38jNLduimUl+qcLKkdVBXYsHvlYdueB74jNWny2Tv0z+oP9NICNxljvpF/K6LgFfyg==

Using the above URL, the cart was recovered.

Email received on Recovering the cart: http://screencast.com/t/sfbZJRVQ

WooCommerce Order link: http://staging.tychesoftwares.com/woo_khyati/wp-admin/post.php?post=5857&action=edit

After recovering the cart, the record was removed from the Abandoned Orders tab but on the Recovered Orders page, the record was not added. The count on the Order Received page too was not including the recovered order. The Product report tab too did not show the products that were abandoned and recovered.

Recovered Order tab: http://screencast.com/t/6K86uI8kA27F

We need to check where did the recovered order go from the database.

**Comment by Chetna1510** [comment]
I have abandoned a cart as a guest user and I am able to receive abandoned cart reminder email.

Screenshot: https://www.screencast.com/t/jlutfu699

Then I have placed an order from abandoned cart reminder email and my cart is showing on the Recovered Orders tab.

Screenshot: https://www.screencast.com/t/Gu5Gfrig8PoH

I had also tried to replicate the issue by logged-in user. But I am not able to replicate the issue on my local server. So, I am closing this issue.
