### ISSUE TITLE
An error is getting on the Abandoned Orders page.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#641]
**Describe the bug**
Below error is getting on the Abandoned Orders page.

Fatal error: Allowed memory size of 314572800 bytes exhausted (tried to allocate 73728 bytes) in /wordpress/wp-includes/functions.php on line 4609

This error is coming on the client's site when we visit the Abandoned Orders page. I am unable to replicate the same.

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

https://tychesoftwares.freshdesk.com/a/tickets/18633

**Comment by pinalj** [comment]
The issue occurs as the client has 176328 visitor carts present on the site. We're showing the records on pages, but the way its being done needs to be changed

1. We fetch the entire data from the DB
2. Run foreach loop on the same.
3. collect the data in the format it needs to be displayed in
4. Chunk the array and display the data per page.

This needs to be updated. We should fetch the data from the DB in chunks using the LIMIT clause to ensure such issues do not occur.

**Comment by pinalj** [comment]
3.6 Lakh records results in the below error on the page:
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 8388616 bytes) in C:\Users\Dhruvin Shah\Local Sites\localwp\app\public\wp-includes\wp-db.php on line 2000
