### ISSUE TITLE
Abandoned Orders page is displaying as blank on a client site.

### ISSUE THREAD

**Issue by priyanka-tychesoftwares** [TycheSoftwares/Woocommerce-abandon-cart-lite#642]
**Describe the bug**
Abandoned Orders page is displaying as blank on a client's site.

On the dashboard, abandoned orders count is showing 32707.

**Screenshots or Video**
https://www.screencast.com/t/7cmjgZwEA7PM
https://www.screencast.com/t/TE711lWu8q

**Isolating the problem (mark completed items with an [x]):**
 [x] This bug happens with only Abandoned Cart Lite for WooCommerce plugin active
 [ ] This bug happens with a default WordPress theme active, or [Storefront]
 [ ] I can reproduce this bug consistently using the steps above

This issue is occurring on two sites on this client. Access is added there on the ticket.

https://tychesoftwares.freshdesk.com/a/tickets/18612

**Comment by dhruvins** [comment]
Related to #642 where high amount of AC orders were causing issues. This is fixed now.
