### ISSUE TITLE
Console shows some error after activating plugin.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#648]
**Describe the bug**
Console shows some error after activating plugin.

**To Reproduce**
1. on my local I don't have Ac lite plugin install
2. After installing the plugin, plugin page throws an error
https://www.screencast.com/t/6kkqSrZCj

**Expected behavior**
No error should be display

**Comment by dhruvins** [comment]
@apeksha10 this notice might not be coming with AC Lite. Can you please verify by deactivating other plugins?

I was not able to replicate this error with just AC Lite active.

**Comment by apeksha10** [comment]
Yes.. after deactivating other's plugin like on my side orddd lite plugin also activate then the above error not appears.

Hence closed this issue.
