### ISSUE TITLE
The default value in "Cart abandoned cut-off time" is shows blank and Email template Toggle shows Off text.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#659]
**Describe the bug**
The default value in "Cart abandoned cut-off time" is shows blank and Toggle shows Off text.

**To Reproduce**
1. Fresh install
2. Install the plugin (Add new--upload)
3. Default value for the field "Cart abandoned cut-off time" shows blank and email template shows Toggle "Off" text.
https://www.screencast.com/t/vI5LrS3Zp9hz
https://www.screencast.com/t/JNlixn0B 

**Expected behavior**
The default value should be display and Off text should not display.

The above issue is replicate on my local and woo_rashmi.

**Comment by pinalj** [comment]
The reason the toggle button is not displayed correctly is that the requisite CSS & JS files are not being loaded. The plugin folder is incorrectly named. It should be 'woocommerce-abandoned-cart' instead of 'Woocommerce-abandon-cart-lite'
