### ISSUE TITLE
Same visitor cart listed many times in the Abandoned order tab.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#666]
**Describe the bug**
Same visitor cart listed many times in the Abandoned order tab.

**To Reproduce**
1. "Start tracking from Cart Page" setting enabled
2. Add the product to the cart page
3. do not visit the checkout page, I just closed the browser on the cart page 
4. Cut off time pass and visitor cart listed in the abandoned order tab
But the issue is the same visitor cart listed many times
see the screenshot: https://www.screencast.com/t/fSsOM9Lcp

**Expected behavior**
The same visitor cart does not display many times

**Comment by pinalj** [comment]
Multiple visitor carts are logged when recovering a cart. This has been fixed in https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/pull/674/commits/9965d66e988bde303fe93e6a4f911705ba3b73a9

However, I found an issue where visitor carts are not being tracked.
