### ISSUE TITLE
Notice displayed on the Order Received page for guest user

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#67]
A guest cart was abandoned when v2.7 installed, the plugin was updated to v2.8 and then GitHub copy was replaced. The emails were sent to the guest user . The user then places the order from the same window where he had abandoned the cart. On the Order Received page, I am getting this notice. 
http://screencast.com/t/YqYcawhkr38O

**Comment by bhavik-kiri** [comment]
I have followed the same scenario on my local machine.

I have abandoned a guest cart with version 2.7. once I have received the reminder emails. I have updated the version 2.8 from the update notification displayed on the plugins page.

Then I have replaced the Git hub copy.

Then I have placed the same order from the same window. But it was not showing a notice.

Please check the screenshot: http://screencast.com/t/kr5Fnl1GupV

**Comment by Chetna1510** [comment]
The commit ( 29550715302869c620cbc9e63087a9ef245b55d4 ) has been fixed for issue #171 .

For this issue, I am unable to replicate. So, I am closing this ticket.

I have checked the issue with the WooCommerce version 3.2.6 and our plugin's latest github copy 4.5, I have abandoned a cart and then I have placed the same order from the same window. But it was not showing a notice.

Please check the screenshot: https://www.screencast.com/t/nt48I50zkRD5
