### ISSUE TITLE
'pm#' word display in the test email. 

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#671]
**Describe the bug**
'pm#' word display in the test email. 

**To Reproduce**
1. Create a New email template with all merge tags.https://www.screencast.com/t/5HUrvKaCr
2. Send a test email, all merge tag replace their real value but Unsubscribe merge tag replaced with 'pm#'
https://www.screencast.com/t/mX909R8C

**Expected behavior**
Unsubscribe merge tag should be replaced their real value.

**Comment by pinalj** [comment]
Not an issue
The unsubscribe link is simply displayed as # for test emails. In the test case mentioned above pm is for the time for the merge tag {{cart.abandoned_date}}. Since there's no space between the two tags, it appears together.
