### ISSUE TITLE
Product report tab Does not shows correct information.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#673]
**Describe the bug**
The product report tab Does not show the correct information.

**To Reproduce**
1. I abandoned Bennie product as guest users
2. after cut off time reminder email received
3. from the reminder email I click on the cart link
4. delete remove an existing product that is Bennie product and add a new product that is Cap product  
5. place an order
6. go to the Product report tab, Cap product information does not displayed
https://www.screencast.com/t/F2ysFRgN

**Expected behavior**
The latest added product information should be added to the Product Report tab.

**Comment by pinalj** [comment]
Unable to replicate the issue. The new product is displayed in the list in the Product Report tab after the cut off time is complete.

**Comment by apeksha10** [comment]
With the latest git copy, I am not able to replicate the above issue.

hence put Fix label.
