### ISSUE TITLE
Bulk action--Delete not working.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#677]
**Describe the bug**
Bulk action--Delete not working.

**To Reproduce**
1. Add 3 email template
2. try to delete that template using bulk action
but the email template does not get deleted
see the video: https://www.screencast.com/t/8cwjsxX4Aipp

Note: Delete button for individual working fine

**Expected behavior**
Bulk action should work fine.

**Comment by pinalj** [comment]
The issue is present in version 5.8.1 as well.
