### ISSUE TITLE
'Shown here' a link from email template shows broad preview.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#691]
**Describe the bug**
'Shown here' a link from the email template shows a broad preview.

**To Reproduce**
1. Create a new email template
2. Set all merged tag
3. click on the 'Shown here' link but it shows a very broad preview

see the screenshot: https://www.screencast.com/t/LprrX0An
https://www.screencast.com/t/g5Lf6HueRv

**Expected behavior**
A preview should be displayed in the proper size

**Comment by pinalj** [comment]
Not an issue. The email template has no CSS, only merge tags. Hence the same is reflected in the preview as well.
