### ISSUE TITLE
Your Shopping Cart title shows the right-aligned in the test email.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#692]
**Describe the bug**
Your Shopping Cart title shows the right-aligned in the test email.

**To Reproduce**
1. Create a new email template
2. Assign all merged tag
3. Click on the Send a test email button
4. Test email received fine but "Your Shopping Cart" title is the right site aligned

see the screenshot: https://www.screencast.com/t/VwJL6Qh0T

**Expected behavior**
The title should display left-aligned.

**Comment by pinalj** [comment]
Email HTML:
<div style="border: 1px solid black; width: 70%; margin: auto;"><p>Hi {{customer.firstname}},</p><p>We noticed you have abandoned a cart on {{cart.abandoned_date}}</p><p>{{products.cart}}</p><p>Thanks,</p></div><p>&nbsp;</p>

Actual reminder email:
https://www.screencast.com/t/pyEsPTtG5PI

**Comment by apeksha10** [comment]
yes.. after uploading the above CSS, it is working fine

Hense closed this issue.
