### ISSUE TITLE
The default email template does not appear.

### ISSUE THREAD

**Issue by apeksha10** [TycheSoftwares/Woocommerce-abandon-cart-lite#701]
**Describe the bug**
The default email template does not appear.

**To Reproduce**
1. On my local, Ac lite plugin is not installed
2. I have installed the first time  
3. activate the plugin
4. go to the email template tab, but no default email template is there
see the screenshot: https://prnt.sc/vpppb2
PHP version is 7. 4.12 

Note: the above issue is not specifically replicated with WP 5.6 beta 2 copy.I have even tried with WP 5.5.3 but no luck. 

**Expected behavior**
The default email template should appear.

**Comment by pinalj** [comment]
Closed in https://github.com/TycheSoftwares/Woocommerce-abandon-cart-lite/pull/704/commits/4a3f7dca35c95f0121911bba67cd64cc89be5c8c
