### ISSUE TITLE
The test email should apply the tax as per set in WooCommere Tax

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#74]
I have set Standard Rate tax set to 1.000%. When the test email is sent, the tax is getting charged at 4%. And there is nowhere mentioned in the plugin that the tax in the test email will be applied at 4%. The test email should show the tax as per the tax added in WooCommerce Tax.

**Comment by Chetna1510** [comment]
We are not adding the feature to display tax in the Lite version. We have added it in the Pro version.
