### ISSUE TITLE
Tax field getting added in the email when Tax is disabled from WooCommerce

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#75]
When Tax is disabled from WooCommerce and 'Display Taxes separately' setting from our plugin is enabled, then the email received from our plugin for abandoned carts has a row added for Tax with price as $0.

If Tax is disabled from WooCommerce, then the row should not be added to the email.

http://screencast.com/t/Bp0YN8Vg

**Comment by Chetna1510** [comment]
We are not adding the feature to display tax in the Lite version. We have added it in the Pro version.

**Comment by ashokrane** [comment]
Ok. In that case, please add this as an item on What is possible in the Pro
plugin section on the WordPress.org plugin page.

:Vishal
