### ISSUE TITLE
Change the tooltip for 'Display Taxes separately' setting

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#77]
Change the tooltip from:

If this is unchecked, taxes will be added in the product price & no separate row for Tax will be shown in the Abandoned Cart email notification as shown here. Otherwise a separate row for Tax will be displayed in the email as shown here.

to:

If this is unchecked, taxes will be added to the product price & no separate row for Tax will be shown in the Abandoned Cart email notification as shown here. Otherwise, a separate row for Tax will be displayed in the Abandoned Cart email notification as shown here.

**Comment by Chetna1510** [comment]
We are not adding the feature to display tax in the Lite version. We have added it in the Pro version.
