### ISSUE TITLE
Add a note next to 'Display Taxes separately'

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#78]
Add a note next to 'Display Taxes separately' setting saying that "For showing the applied tax separately, Tax should be enabled under WooCommerce -> Settings -> General tab. And if Tax is disabled from WooCommerce then a new row for tax will not be displayed in the reminder email notification."

**Comment by Chetna1510** [comment]
We are not adding the feature to display tax in the Lite version. We have added it in the Pro version.
