### ISSUE TITLE
Tax should not be displayed in Test / preview email when Tax is disabled from WooCommerce

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#79]
When Tax is disabled from WooCommerce & 'Display Taxes separately' setting is enabled from our plugin, then the tax should not be applied to the test email or in the preview email. (With or without WooCommerce email template).

Test email: http://screencast.com/t/TjDkM00V
Preview email with WooCommerce email template: http://screencast.com/t/uYW5MwJvuF
Preview email without WooCommerce email template: http://screencast.com/t/smEPZzpK5

**Comment by Chetna1510** [comment]
We are not adding the feature to display tax in the Lite version. We have added it in the Pro version.
