### ISSUE TITLE
The text from WordPress is coming shifted on the Email Templates page

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#81]
The text 'Thank you for creating with WordPress.' is coming shifted to the right on the Email Template page rather than coming on the left corner of the page. 

http://screencast.com/t/BzIQJJLe

On other pages, it is coming correctly: http://screencast.com/t/aqk4Tg3akDuH

**Comment by Chetna1510** [comment]
This issue has been fixed in the commit: 1df2b18b33c1f8256fcfbdcc45a0c1e92f0e0768
