### ISSUE TITLE
Getting wrong cart content for guest user

### ISSUE THREAD

**Issue by galakhyati** [TycheSoftwares/Woocommerce-abandon-cart-lite#90]
A guest user abandoned a cart, reminder emails were sent to the user, using the cart link the cart was accessed to recover the cart. The cart was abandoned for 'Gamebore Blue Diamond 1-1/8oz 1285fps
Size: 8 ' product. But on accessing the cart URL from email, the cart is showing 'Drum set' product.

Abandoned detail: http://screencast.com/t/wbpBep7b
Cart:http://screencast.com/t/De7Oty3d4Cc
URL used: http://staging.tychesoftwares.com/woo_aclite/?wcal_action=track_links&validate=HgGFpJQFk1eB8B3X7KAnyu3f7tTSuKAmXVHRLpvjh4ZmxGwbQYPhjSZ1tVYIgosyCxKeNGXzX4UFZ14MCeXw0em7

**Comment by bhavik-kiri** [comment]
It may be the issue because the site has PRO version installed, so while restoring the guest cart it is referring the guest users cart which was abandoned by the PRO plugin. As the guest user id is same for the Pro and Lite version. And then it is populating the wrong cart.
