### ISSUE TITLE
Price should be comming with comma separator 

### ISSUE THREAD

**Issue by Chetna1510** [TycheSoftwares/Woocommerce-abandon-cart-lite#94]
We are displaying the price  $74849.83 for abandoned cart and recovered cart. The price should be $74,849.83 with the comma separator on all the page where we are displaying the amount .

**Comment by ashokrane** [comment]
Please make sure this is fixed for both lite & pro versions.

**Comment by Chetna1510** [comment]
This has been fixed in the commit: 5b3f2f5cd55412532319e75c683c20cc1be88ce1
